#!/bin/bash

# This script will build rakudo for all commits that it can find

export WORKING_DIRECTORY='.' # TODO not supported yet
export RAKUDO_LOCATION="$WORKING_DIRECTORY/rakudo"
RAKUDO_ORIGIN='https://github.com/rakudo/rakudo.git'
TEST_LOCK="$WORKING_DIRECTORY/lock"
PARALLEL_COUNT=7

clean() {
    while popd &> /dev/null; do :; done # change directory back
    rmdir -- "$TEST_LOCK"
}

if mkdir -p -- "$TEST_LOCK"; then # only one instance running
    trap clean EXIT
else
    exit 0
fi

if [[ -d $RAKUDO_LOCATION ]]; then
    pushd -- "$RAKUDO_LOCATION" || exit 1
    git pull
    popd
else
    git clone -- "$RAKUDO_ORIGIN" "$RAKUDO_LOCATION"
fi

git_orig=('git' '--git-dir' "$RAKUDO_LOCATION/.git" '--work-tree' "$RAKUDO_LOCATION")

# you can change v6.c...HEAD to something else
"${git_orig[@]}" log -z --pretty='%H' v6.c...HEAD \
    | xargs -0 -n 1 -P "$PARALLEL_COUNT" ./process-sha
